AutoUpdate: true

PanicTolerance: 2
PanicWords:
  - grief
  - griefer
  - griefing
  - griefed
  - hack
  - hacker
  - hacking
  - hacked
  - hacks
  - help
  - need

IssueLifetimeInDays: 3
MinutesBetweenUnresolvedIssueNotifications: 5
SecondsBetweenChangedIssueSaves: 30
