name: Tidy
description: Simple issue tracking and management
version: 1.0
author: makskay
website: http://dev.bukkit.org/server-mods/Tidy

main: me.makskay.tidy.TidyPlugin

commands:
  comment:
    description: Adds a comment to an issue.
    usage: /<command> <issue ID> <comment>
    permission: tidy.user
    permission-message: You don't have permission to comment on issues!
  helpme:
    description: Requests help from the server staff.
    usage: /<command> <issue description>
    permission: tidy.user
    permission-message: You don't have permission to request help with an issue!
  investigate:
    description: Teleports to the saved location for an issue.
    usage: /<command> <issue ID>
    permission: tidy.staff
    permission-message: You don't have permission to investigate issues!
  issue:
    description: Prints detailed information about an issue.
    usage: /<command> <issue ID>
    permission: tidy.user
    permission-message: You don't have permission to view detailed issue information!
  issues:
    description: Lists issue reports.
    usage: /<command> [page number] [-all]
    permission: tidy.user
    permission-message: You don't have permission to list issue reports!
  reopen:
    description: Marks a resolved issue as open.
    usage: /<command> <issue ID> <reason>
    permission: tidy.user
    permission-message: You don't have permission to mark issues as open!
  resolve:
    description: Marks an open issue as resolved.
    usage: /<command> <issue ID> <reason>
    permission: tidy.user
    permission-message: You don't have permission to mark issues as resolved!
  sticky:
    description: Marks an issue as sticky (persistent even if marked resolved).
    usage: /<command> <issue ID> <reason>
    permission: tidy.staff
    permission-message: You don't have permission to mark issues as sticky!
  desticky:
    description: Marks an issue as non-sticky (will expire as normal).
    usage: /<command> <issue ID> <reason>
    permission: tidy.staff
    permission-message: You don't have permission to mark issues as non-sticky!

permissions:
  tidy.user:
    description: Gives access to Tidy's basic user-level commands
    default: true
  tidy.staff:
    description: Gives access to Tidy's global issue-management commands
    default: op
  tidy.admin:
    description: Gives access to Tidy's high-level configuration-related commands
    default: op